UNIFORM_COST = 0.001
API_COST = {
    "API1": UNIFORM_COST,
    "API2": UNIFORM_COST,
    "API3": UNIFORM_COST,
    "API4": UNIFORM_COST,
}
LOGGER_ALLOWED_NAMESPACES = ['payg']
LOGGER_ALLOWED_STATUS_CODES = [200, 201, 202, 203, 204]
